version: 0.1

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install --user aws-sam-cli
      - /root/.local/bin/sam --version
      # - unit tests
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - /root/.local/bin/sam package --template-file services/PuzzleApi/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file puzzle-packaged.yaml
      - /root/.local/bin/sam package --template-file services/solvePuzzle/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file solvePuzzle-packaged.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - puzzle-packaged.yaml
    - solvePuzzle-packaged.yaml
  discard-paths: yes
