version: 0.1

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install --user pytest moto boto3
      - /root/.local/bin/pytest --version
  build:
    commands:
      - /root/.local/bin/pytest services/tryNewPuzzle/tests/
      - /root/.local/bin/pytest services/getNewPuzzleSolution/tests/
      - /root/.local/bin/pytest services/solvePuzzle/tests/
