version: 0.1

phases:
  pre_build:
    commands:
      - python --version
      - python3 --version
      - pip install --upgrade pip
      - pip install --user aws-sam-cli
      # - echo "Installing dependencies - `pwd`"
      # - unit tests
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - sam package --template-file services/tryNewPuzzle/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file tryNewPuzzle-packaged.yaml
      # - aws cloudformation package --template-file services/tryNewPuzzle/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file tryNewPuzzle-packaged.yaml
      # - aws cloudformation package --template-file test-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file test-output_sam.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - tryNewPuzzle-packaged.yaml
  discard-paths: yes
