version: 0.1

phases:
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file services/tryNewPuzzle/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file tryNewPuzzle-packaged.yaml
      # - aws cloudformation package --template-file test-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file test-output_sam.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - tryNewPuzzle-packaged.yaml
  discard-paths: yes
