AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless resources for SudokuServerless application

Resources:
    GetPuzzleFunction:
        Type: AWS::Serverless::Function 
        Properties:
            Handler: application/get_puzzle.handler
            Runtime: python3.6
            Description: Gets an unsolved puzzle from an s3 bucket
            Environment:
                Variables:
                    UNSOLVED_BUCKET_NAME: VALUE
            Events:
                GetNewPuzzle:
                    Type: Api
                    Properties:
                        Path: /getNewPuzzle
                        Method: get

    SudokuUnsolvedPuzzlesBucket:
        Type: 'AWS::S3::Bucket'
        Properties:
          BucketName: 'sudoku-unsolved-puzzles'

Outputs:
    GetPuzzleFunctionApi:
      Description: "API Gateway endpoint URL for Prod stage for GetPuzzleFunction function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    GetPuzzleFunction:
      Description: "GetPuzzleFunction Lambda Function ARN"
      Value: !GetAtt GetPuzzleFunction.Arn

    GetPuzzleFunctionIamRole:
      Description: "Implicit IAM Role created for GetPuzzleFunction function"
      Value: !GetAtt GetPuzzleFunctionRole.Arn
    
    SudokuUnsolvedPuzzlesBucket:
        Description: "Bucket used to store unsolved sudoku puzzles"
        Value: SudokuUnsolvedPuzzlesBucket
