AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a static website using S3 for the Wild Rydes serverless web application workshop

Parameters:
  BucketName:
    Type: String
    Description: The name for the bucket hosting your website, e.g. 'sudoku-serverless'
    Default: sudoku-serverless

Resources:
  WebsiteBucket:
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: "AWS::S3::Bucket"

  WebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: SudokuServerless
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: SudokuServerlessWeb
      UserPoolId: !Ref UserPool
      GenerateSecret: false

  TryNewPuzzleBuildsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-trynewpuzzle-builds"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  UnsolvedPuzzlesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'sudoku-unsolved-puzzles'

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL

  userPoolId:
    Value: !Ref UserPool

  userPoolClientId:
    Value: !Ref UserPoolClient
