AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a static website using S3 for the Wild Rydes serverless web application workshop

Parameters:
  BucketName:
    Type: String
    Description: The name for the bucket hosting your website, e.g. 'sudoku-serverless'
    Default: sudoku-serverless
  Environment:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
      - test

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Resources:
  WebsiteBucket:
    Properties:
      BucketName: !If [Prod, !Ref BucketName, !Sub '${BucketName}-${Environment}']
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: "AWS::S3::Bucket"

  WebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  UserPool:
    Type: AWS::Cognito::UserPool
    Condition: Prod
    Properties:
      UserPoolName: SudokuServerless
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Condition: Prod
    Properties:
      ClientName: SudokuServerlessWeb
      UserPoolId: !Ref UserPool
      GenerateSecret: false

  UnsolvedPuzzleSolutionsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'sudoku-unsolved-puzzle-solutions-${Environment}'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL

  userPoolId:
    Condition: Prod
    Value: !Ref UserPool

  userPoolClientId:
    Condition: Prod
    Value: !Ref UserPoolClient
