baseURL = "/"
languageCode = "en-us"
title = "Sudoku Serverless"
theme = "kube"
Paginate = 4
[Params]
  description = "A Serverless demo application using AWS"

[[menu.main]]
    name = "Try"
    weight = -100
    url = "/try/"
[[menu.main]]
    name = "Solve"
    weight = -100
    url = "/solve/"
[[menu.extra]]
    name = "Account"
    url = "/account/"
