AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless resources for puzzle service

Parameters:
  Environment:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
      - test
    ConstraintDescription: must specify prod, staging, dev or test.
  ServiceName:
    Description: Service name.
    Default: puzzle
    Type: String
  Description:
    Description: Description of service.
    Default: Provides methods for retrieving unsolved and solved puzzles from s3 buckets.
    Type: String
  UnsolvedBucketPrefix:
    Description: Description of service.
    Default: sudokuless-unsolved
    Type: String
  SolvedBucketPrefix:
    Description: Description of service.
    Default: sudokuless-solved
    Type: String


Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
          MetricsEnabled: false
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: !Sub '${ServiceName}-${Environment}'
        schemes:
        - "https"
        paths:
          "/puzzle":
            get:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UnsolvedFunction.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: "{}\n"
                requestTemplates:
                  application/json: "{\n  \"statusCode\" : 200\n}\n"
                passthroughBehavior: "when_no_match"
                type: "mock"
          "/puzzle/{id}":
            get:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SolvedFunction.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: "{}\n"
                requestTemplates:
                  application/json: "{\n  \"statusCode\" : 200\n}\n"
                passthroughBehavior: "when_no_match"
                type: "mock"
        securityDefinitions:
          sigv4:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "awsSigv4"

  Default400GatewayResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
        ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref Api

  Default500GatewayResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
        ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref Api

  UnsolvedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ServiceName}-unsolved-${Environment}'
      Handler: puzzle/unsolved.handler
      Runtime: python3.6
      MemorySize: 512
      Timeout: 3
      Description: !Ref Description
      Role: !GetAtt FunctionRole.Arn
      Environment:
        Variables:
          UNSOLVED_BUCKET_NAME: !Ref UnsolvedBucket
      Events:
        UnsolvedPuzzle:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /puzzle
            Method: GET

  SolvedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ServiceName}-solved-${Environment}'
      Handler: puzzle/solved.handler
      Runtime: python3.6
      MemorySize: 512
      Timeout: 3
      Description: !Ref Description
      Role: !GetAtt FunctionRole.Arn
      Environment:
        Variables:
          SOLVED_BUCKET_NAME: !Ref SolvedBucket
      Events:
        SolvedPuzzle:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /puzzle/{id}
            Method: GET

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ServiceName}-${Environment}-Role'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
          - PolicyName: S3PuzzleBucketAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                  - Action:
                      - 's3:GetObject'
                      - 's3:ListBucket'
                    Effect: Allow
                    Resource:
                      - !Sub "arn:aws:s3:::${UnsolvedBucket}"
                      - !Sub "arn:aws:s3:::${UnsolvedBucket}/*"
                      - !Sub "arn:aws:s3:::${SolvedBucket}"
                      - !Sub "arn:aws:s3:::${SolvedBucket}/*"

  UnsolvedBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${UnsolvedBucketPrefix}-${Environment}'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  SolvedBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${SolvedBucketPrefix}-${Environment}'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL for stage of Service
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/${ServiceName}/'

  ApiId:
    Description: ID for the API
    Value: !Ref Api

  UnsolvedBucketName:
    Description: Unsolved Bucket Name
    Value: !Ref UnsolvedBucket

  SolvedBucketName:
    Description: Solved Bucket Name
    Value: !Ref SolvedBucket

  FunctionIamRole:
    Description: Implicit IAM Role created for function
    Value: !GetAtt FunctionRole.Arn
